name: build

on:
  push:
    branches:
      - main

jobs:
  build_memcached:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      build-args: |
        MEMCACHED_VERSION=1.6.18
      image_tag: |
        latest
        1.6.20-bullseye-r1 # renovate: datasource=github-tags depName=memcached/memcached
        1.6.20-bullseye # renovate: datasource=github-tags depName=memcached/memcached
        1.6.20 # renovate: datasource=github-tags depName=memcached/memcached
        1.6
        1
    secrets: inherit
