name: build

on:
  push:
    branches:
      - main

jobs:
  build_memcached:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      build-args: |
        MEMCACHED_VERSION=1.6.20 # renovate: datasource=github-tags depName=memcached/memcached
      version: 1.6.20 # renovate: datasource=github-tags depName=memcached/memcached
      major_only_tag: true
    secrets: inherit
